name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable
      
      - name: Install foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: latest
        env:
          FOUNDRY_DISABLE_NIGHTLY_WARNING: 1

      - name: Run foundry node, deploy contracts (& generate contracts typescript output)
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          yarn chain & sleep 5
          yarn deploy

      - name: Run nextjs lint
        run: yarn next:lint

      - name: Check typings on nextjs
        run: yarn next:check-types